src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Holdings__c</fullName>
        <label>Current Holdings</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>false</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (From Account)</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>From_Role__c</fullName>
        <label>From Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Account Holder</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You must select an Individual/Person Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BXm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BPO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (To Account)</relationshipLabel>
        <relationshipName>Account_Relationships_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Role__c</fullName>
        <label>To Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Power of Attorney</fullName>
                </value>
                <value>
                    <fullName>Executor</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referrer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Metal_Price__c.object
<CustomObject>
    <description>Custom object to hold metal prices</description>
    <fields>
        <fullName>Price_Date__c</fullName>
        <description>Imported price date</description>
        <label>Price Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>The worth of metal</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Metal Price</label>
    <nameField>
        <label>Metal Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metal Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static string GetRecordTypeIdByName(String recTypeName){    
        List<RecordType> recTypeList = [select id,name,sobjectType,ispersontype from recordType where isActive = true and sObjectType ='Account'];
        //List<recordType> recTypeList ;
        for(RecordType rt : recTypeList){
            if(rt.name == recTypeName) return rt.Id;
        }
        return null;
    }
    
    public static Account CreateAccountByName(String accountName){        
        Account acc = new Account();
        acc.Salutation = 'Mr.';
        acc.FirstName ='TestName';
        acc.LastName = accountName;
        acc.RecordTypeId=  GetRecordTypeIdByName('Individual Account');
        acc.BillingStreet ='123 '+accountName+' street';
        acc.BillingCity='Los Angeles';
        acc.BillingPostalCode ='90046';
            acc.BillingState = 'California';
            acc.BillingCountry = 'United States';
        acc.Current_Holdings__c = 100.00;
        return acc;
    }
    
     public static Account CreateEstateAccountByName(String accountName){        
        Account acc = new Account();
        acc.Name =accountName;        
        acc.RecordTypeId=  GetRecordTypeIdByName('Estate Account');
        acc.BillingStreet ='333 '+accountName+' street';
        acc.BillingCity='Los Angeles';
        acc.BillingPostalCode ='90046';
            acc.BillingState = 'California';
            acc.BillingCountry = 'United States';
        acc.Current_Holdings__c = 500.00;
        return acc;
    }
    //Create given number amount of accounts
    public static List<Account> CreateAccountsforDuplicateRules(Integer numAccts){
        List<Account> paList = new list<Account>();
       ID recID = GetRecordTypeIdByName('Individual Account');
        
        for(integer i=0; i<numAccts; i++){
            Account pa = new Account();
            pa.Salutation = 'Mr.';
            pa.FirstName = 'test '+i;
            pa.LastName = 'test last name';
            pa.PersonEmail = 'test@gmail.com';
            pa.BillingStreet ='111 test street';
            pa.BillingCity='Los Angeles';
            pa.BillingPostalCode ='90046';
            pa.BillingState = 'California';
            pa.BillingCountry = 'United States';
            pa.Current_Holdings__c = 100;
            paList.add(pa);
            pa.RecordTypeId = recID;
          //  Database.SaveResult saveResult = Database.insert(pa, DML);
        }
        
        return paList;
    }
    
    //Create only single account
    public static Account CreateSingleAccountforDuplicateRules()
    {
        Account paNew = new Account();
        paNew.Salutation = 'Mr.';
        paNew.FirstName = 'test';
        paNew.LastName = 'test last name';
        paNew.PersonEmail = 'test@test.com';
        paNew.BillingStreet ='111 test street';
        paNew.BillingCity='Los Angeles';
        paNew.BillingPostalCode ='90046';
        paNew.BillingState = 'California';
        paNew.BillingCountry = 'United States';
        paNew.Current_Holdings__c = 100;
        paNew.RecordTypeId = GetRecordTypeIdByName('Individual Account');
        
        return paNew;
    }
	//Create a single account that will pass the duplicate rules
    public static Account CreateSingleAccountwithNoDuplicateError()
    {
        Account paNew = new Account();
        paNew.Salutation = 'Mr.';
        paNew.FirstName = 'gold';
        paNew.LastName = 'line';
        paNew.PersonEmail = 'goldline@goldline.com';
        paNew.BillingStreet ='123 Olympic street';
        paNew.BillingCity='Los Angeles';
        paNew.BillingPostalCode ='90001';
        paNew.BillingState = 'California';
        paNew.BillingCountry = 'United States';
        paNew.Current_Holdings__c = 100;
        paNew.RecordTypeId = GetRecordTypeIdByName('Individual Account');
        
        return paNew;
    }
    public static List<Metal_Price__c> CreateStockPrices(){
        List<Metal_Price__c> StockPriceList = new List<Metal_Price__c>();
        Metal_Price__c GoldPrice = new Metal_Price__c();
        GoldPrice.Name = 'Gold';
        GoldPrice.Price__c =123.98;
        GoldPrice.Price_Date__c = Date.today();
        StockPriceList.add(GoldPrice);
        
        Metal_Price__c SilverPrice = new Metal_Price__c();
        SilverPrice.Name = 'Silver';
        SilverPrice.Price__c =99.98;
        SilverPrice.Price_Date__c = Date.today();
        StockPriceList.add(SilverPrice);
        
        Metal_Price__c PlatinumPrice = new Metal_Price__c();
        PlatinumPrice.Name = 'Platinum';
        PlatinumPrice.Price__c =88.98;
        PlatinumPrice.Price_Date__c = Date.today();
        StockPriceList.add(PlatinumPrice);
        
        Metal_Price__c PalladiumPrice = new Metal_Price__c();
        PalladiumPrice.Name = 'Palladium';
        PalladiumPrice.Price__c =55.98;
        PalladiumPrice.Price_Date__c = Date.today();
        StockPriceList.add(PalladiumPrice);
        
        return StockPriceList;
    }
    
    public static Account_Relationship__c CreateAccountRelationship(String FromID, String ToID){
        Account_Relationship__c aRel  = new Account_Relationship__c();
        aRel.From_Account__c = FromID;
        aRel.From_Role__c='Primary Account Holder';
        aRel.To_Account__c = ToId;
        aRel.To_Role__c = 'Executor';
        
        return aRel;
    }
}