src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>false</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Phone_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Phone Relationships</relationshipLabel>
        <relationshipName>Account_Phone_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Primary_Phone_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number_Type__c</fullName>
        <label>Phone Number Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cell</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <isActive>false</isActive>
                    <label>Mobile</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phone Number</label>
        <referenceTo>PhoneNumber__c</referenceTo>
        <relationshipLabel>Account Phone Relationships</relationshipLabel>
        <relationshipName>Account_Phone_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Phone Relationship</label>
    <nameField>
        <displayFormat>APRelationship-{YYYY}{00000}</displayFormat>
        <label>Account Phone Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PhoneNumber__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PhoneNumberTests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Phone Number</label>
    <nameField>
        <label>Phone Number Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ControllerPhoneList.cls
public class ControllerPhoneList {
    // Controller extension for the PhoneListPage Visualforce Page.
    private List<Account_Phone_Relationship__c> phoneNumberList;
    public Task theTask {get;set;}
    public Id accountID {get;set;}
    public String accountName {get;set;}
    public String subjectForNewTaskFromOldTaskIfNeeded {get;set;}
    
    public ControllerPhoneList(ApexPages.StandardController Account){
        
        if (ApexPages.currentPage().getParameters().get('taskId') != null && ApexPages.currentPage().getParameters().get('taskId') != ''){
            
            theTask = [SELECT Id, Owner.Id, WhatId, ActivityDate, Subject, Description FROM Task 
                       WHERE Id = :ApexPages.currentPage().getParameters().get('taskId')];
            
            accountID = theTask.WhatId;
            
        } else {
            
            accountID = ApexPages.currentPage().getParameters().get('accountId');    
            subjectForNewTaskFromOldTaskIfNeeded = ApexPages.currentPage().getParameters().get('oldTaskSubject');
            
        }

    }    
    
    public List<Account_Phone_Relationship__c> getPhoneNumberList(){
        
        phoneNumberList = [SELECT Id, Phone_Number__r.Phone_Number__c, Phone_Number_Type__c, Is_Primary_Phone_del__c, Account__r.Name FROM Account_Phone_Relationship__c WHERE Account__c = :accountID];
        
        if (!phoneNumberList.isEmpty()){
            accountName = phoneNumberList[0].Account__r.Name;  
        } else {
            System.debug('No phone numbers returned for this account.');
        }
        
        return phoneNumberList;
        
    }

}