src/objects/Account_Phone_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Phone Relationships</relationshipLabel>
        <relationshipName>Account_Phone_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phone Number</label>
        <referenceTo>PhoneNumber__c</referenceTo>
        <relationshipLabel>Account Phone Relationships</relationshipLabel>
        <relationshipName>Account_Phone_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Phone Relationship</label>
    <nameField>
        <displayFormat>APRelationship-{YYYY}{00000}</displayFormat>
        <label>Account Phone Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Area_Code__c.object
<CustomObject>
    <description>Phone Area Code</description>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Phone area code</description>
        <label>Area Code</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Area_State_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area State Code</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Area Codes</relationshipLabel>
        <relationshipName>Area_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Abbreviation__c</fullName>
        <label>State Abbreviation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviation</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State Picklist</description>
        <inlineHelpText>Choose the State</inlineHelpText>
        <label>State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>Area Code</label>
    <nameField>
        <label>Area Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Area Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PhoneNumber__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PhoneNumberTests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area_Code__c</fullName>
        <label>Area Code</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Phone Number</label>
    <nameField>
        <label>Phone Number Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Call_End_Time__c</fullName>
        <label>Calling End Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Call_Start_Time__c</fullName>
        <label>Calling Start Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>State_Abbreviation__c</fullName>
        <label>State Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Abbreviation</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Zone_Offset__c</fullName>
        <description>Time Zone Offset from pacific</description>
        <label>Time Zone Offset</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Telemarketing_time__c.object
<CustomObject>
    <description>Telemarketing Time and Holiday Block</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date of Telemarketing</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of Telemarketing</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Telemarketing Times</relationshipLabel>
        <relationshipName>Telemarketing_Times</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Telemarketing Time</label>
    <nameField>
        <label>Telemarketing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telemarketing Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/State.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>District of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <description>State Picklist</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

src/globalValueSets/State_Abbreviation.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>State Abbreviation</masterLabel>
</GlobalValueSet>

src/classes/GetTelemarketValidation.cls
public class GetTelemarketValidation {       
    //This Method will return phone number and phone number area code in map <PhoneNumber,AreaCode>
    private static Map<String,String> parseAreaCode(List<String> PhoneNumberList){
        List<String> AreaCode = new List<String>();
        Map<String,String> phoneAreaCodeMap = new Map<String,String>();
        String PhoneNumber;
        Pattern p = Pattern.compile('[-() +]');
        for(String num : PhoneNumberList){
            PhoneNumber = p.matcher(num).replaceAll('');            
            if(PhoneNumber.length() == 10){            	
                phoneAreaCodeMap.put(PhoneNumber, PhoneNumber.substring(0, 3));
            }else if(PhoneNumber.length()>10){
                phoneAreaCodeMap.put(PhoneNumber, PhoneNumber.substring(1, 4));             
            }
        }     
        return phoneAreaCodeMap;        
    }
    
    //Return list of state based on the areacodes passed in Map<PhoneNumber,StateName>
    private static Map<String,Area_Code__c> returnPhoneStateMap(Map<String,String> phoneAreaCodeMap){
        Map<String,Area_Code__c> returnPhoneAreaCodeMap = new Map<String,Area_Code__c>();
        List<Integer> codes = new List<Integer>();
        Integer x=0;
        for(String ac:phoneAreaCodeMap.values()){           
            codes.add(integer.valueof(ac));
        }       
        List<Area_Code__c> areaCodeList = new List<Area_Code__c>();
        areaCodeList = [
            Select Name
            ,Area_Code__c
            ,State__c
            ,State_Abbreviation__c
            ,Area_State_Code__r.Id
            ,Area_State_Code__r.Time_Zone_Offset__c
            ,Area_State_Code__r.Call_Start_Time__c
            ,Area_State_Code__r.Call_End_Time__c
            FROM Area_Code__c
            Where Area_Code__c IN : codes       
        ];
        State__c currentState = new State__c();
        for(String keyValue:phoneAreaCodeMap.keySet()){            
            for(Area_Code__c state: areaCodeList){
                if(phoneAreaCodeMap.get(keyValue) == state.Name){                  
                    returnPhoneAreaCodeMap.put(keyValue,state); 
                }
            }
        }
        return returnPhoneAreaCodeMap;
    }
    
    
    public Static Map<String,Boolean> getPhoneDialablity(Id acctId){
        //  Map<String,Boolean> phoneDialbilty = new Map<String,Boolean>();
        List<Account_Phone_Relationship__c> acctPhoneRelList;
        List<String> phoneList = new List<String>();
        Map<String,String> phoneAreaCodeMap = new Map<String,String>();
        Map<String,Area_Code__c> PhoneStateMap = new Map<String,Area_Code__c>();
        Map<String,Boolean> PhoneTelemarketingMap = new Map<String,Boolean>();        
        acctPhoneRelList = [SELECT Phone_Number__r.Name, Account__r.Name FROM Account_Phone_Relationship__c WHERE Account__c = :acctId];
        for(Account_Phone_Relationship__c pNum: acctPhoneRelList){
            phoneList.add(pNum.Phone_Number__r.Name);
        }        
        phoneAreaCodeMap = parseAreaCode(phoneList);
        PhoneStateMap = returnPhoneStateMap(phoneAreaCodeMap);      
        return getTelemarketingSchedule(PhoneStateMap);
        
    }
    //Return a map of Phone number and dialable status
    public Static Map<String,Boolean> getTelemarketingSchedule(Map<String,Area_Code__c> phoneStateMap){
        Datetime currentDate = System.now();
		//currentDate= currentDate.addHours(2);
		Time currentTime = currentDate.time();
        Map<String,boolean> PhoneTelemarketingMap = new Map<String,boolean>();
        Map<String,Boolean> PhoneList = new Map<String,Boolean>();       
        Area_Code__c aCode = new Area_Code__c();
        List<String> stateList = new List<String>();
        for(Area_Code__c stateName : PhoneStateMap.values()){
            stateList.add(stateName.Area_State_Code__r.Id);
        }
       
        List<Telemarketing_time__c> teleMarketingList = [SELECT Id, 
                                                         Name, 
                                                         State__c,
                                                         State__r.Name, 
                                                         Start_Date__c, 
                                                         End_Date__c
                                                         FROM Telemarketing_time__c
                                                         Where State__c IN : stateList
                                                         AND Start_Date__c <= :currentDate.date() 
                                                         AND End_Date__c >= :currentDate.date()
                                                        ];
              
        for(string keyValue: phoneStateMap.keySet()){
            Boolean inhours = false;
            aCode = phoneStateMap.get(keyValue);
            if((aCode.Area_State_Code__r.Call_Start_Time__c.addhours(-(Integer)aCode.Area_State_Code__r.Time_Zone_Offset__c) < currentTime 
                && aCode.Area_State_Code__r.Call_End_Time__c.addhours(-(Integer)aCode.Area_State_Code__r.Time_Zone_Offset__c) > currentTime)){
                    //local time is still in call hours of the state                   
                    inhours=true;
                }           
            for(Telemarketing_time__c telemarket : teleMarketingList){
                if((aCode.Area_State_Code__r.Id == telemarket.State__c) || !inHours){
                        PhoneList.put(keyValue, false);                
                }else{
                    PhoneList.put(keyValue, true);
                }
            }
        }     
        return PhoneList;
    } 
}