src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accumulation Client</fullName>
                </value>
                <value>
                    <fullName>Bad Phone Number</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Goldline DNC / DCP</fullName>
                </value>
                <value>
                    <fullName>IRA Client</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Loan Client</fullName>
                </value>
                <value>
                    <fullName>New Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Protected Client</fullName>
                </value>
                <value>
                    <fullName>Protected Prospect</fullName>
                </value>
                <value>
                    <fullName>Reassign</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Unable to Invest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Sales__c</fullName>
        <label>Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Has_Account_Agreement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Account Agreement</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>false</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ControllerClientOverviewPage.cls
public class ControllerClientOverviewPage {
    public String contactIDValue;
    public Account account {get;set;}
    
    public void setcontactIDValue (String conID) {     
        account = [SELECT Id,                     
                   Name,
                   //secondary approver?
                   //lead group
                   BillingState,
                   Account_Status__c ,
                   Has_Account_Agreement__c ,                                        
                   Gross_Sales__c ,
                   Current_Balance__c ,
                   PersonLeadSource,
                   CreatedDate,                  
                   PersonEmail
                   FROM Account 
                   where ID =: conID 
                   LIMIT 1]; 
        contactIDValue = account.Name;
    }
    
    public String getcontactIDValue() {
        return contactIDValue;
    } 
}