src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Agreement_Executed_Date__c</fullName>
        <label>Account Agreement Executed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Agreement_Sent_Date__c</fullName>
        <label>Account Agreement Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Replaces existing Account Number and does not include Loan Accounts; Loan Accounts will have a separate formula field that appends the &quot;L&quot; after the value</description>
        <displayFormat>{00000000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accumulation Client</fullName>
                </value>
                <value>
                    <fullName>Bad Phone Number</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Goldline DNC / DCP</fullName>
                </value>
                <value>
                    <fullName>IRA Client</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Loan Client</fullName>
                </value>
                <value>
                    <fullName>New Lead</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Protected Client</fullName>
                </value>
                <value>
                    <fullName>Protected Prospect</fullName>
                </value>
                <value>
                    <fullName>Reassign</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Unable to Invest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Anniversary__c</fullName>
        <label>Anniversary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Business_Phone__c</fullName>
        <description>Business Phone Placeholder  for Phone Object</description>
        <inlineHelpText>Business Phone</inlineHelpText>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CRM_Account_GUID__c</fullName>
        <externalId>true</externalId>
        <label>CRM Account GUID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_PIN__c</fullName>
        <label>Customer PIN</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_subscription__c</fullName>
        <label>E-Mail subscription</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Loan__c</fullName>
        <label>Is Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Activity_Date__c</fullName>
        <label>Last Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Activity_Related__c</fullName>
        <label>Last Activity Related</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Conversation_Date__c</fullName>
        <label>Last Conversation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Lead_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Lead Source</label>
        <referenceTo>Lead_Source__c</referenceTo>
        <relationshipLabel>Accounts (Last Lead Source)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Divorced</fullName>
                </value>
                <value>
                    <fullName>Widowed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Phone Number place holder of Phone Object</description>
        <inlineHelpText>Mobile Phone Number</inlineHelpText>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Next_Trade_Amount__c</fullName>
        <label>Next Trade Amount</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0 - 5K</fullName>
                </value>
                <value>
                    <fullName>5k - 10k</fullName>
                    <label>5K - 10K</label>
                </value>
                <value>
                    <fullName>10k - 20k</fullName>
                    <label>10K - 20K</label>
                </value>
                <value>
                    <fullName>20K+</fullName>
                </value>
                <value>
                    <fullName>100K+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Trade_Date__c</fullName>
        <label>Next Trade Date</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 Week</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 Week</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 Week</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 Week +</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Trade_Expected_Date__c</fullName>
        <description>Add selected week days to current date</description>
        <formula>NOW() + (VALUE(TEXT(Next_Trade_Date__c))  * 7)</formula>
        <label>Next Trade Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <description>Primary Phone holder from Phone Object</description>
        <inlineHelpText>Primary Phone Number</inlineHelpText>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secondary_Approver__c</fullName>
        <label>Secondary Approver</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spouse_Name__c</fullName>
        <label>Spouse Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Storage_Balance__c</fullName>
        <label>Storage Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Third_Approver__c</fullName>
        <label>Third Approver</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Purchases__c</fullName>
        <label>Total Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Probability__c</fullName>
        <label>Trade Probability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0.25</fullName>
                    <label>0-25%</label>
                </value>
                <value>
                    <fullName>0.50</fullName>
                    <label>25-50%</label>
                </value>
                <value>
                    <fullName>0.75</fullName>
                    <label>50-75%</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>75-100%</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trust_Pilot_Survey_Completed_Date__c</fullName>
        <label>Trust Pilot Survey Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trust_Pilot_Survey_Sent_Date__c</fullName>
        <label>Trust Pilot Survey Sent Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>false</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (From Account)</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>From_Role__c</fullName>
        <label>From Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Account Holder</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You must select an Individual/Person Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BXm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BPO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (To Account)</relationshipLabel>
        <relationshipName>Account_Relationships_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Role__c</fullName>
        <label>To Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Power of Attorney</fullName>
                </value>
                <value>
                    <fullName>Executor</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referrer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ControllerAccountView.cls
public with sharing class ControllerAccountView {
    public String AccountId{get;set;}
    private final Account Acct;
    private string ReportPath;
    public List<RecordType> recTypeList;
    public String AccumulationTypeId;
    public String TrustTypeId;
    public String EstateTypeId;
    public String BusinessTypeId;
    public List<Account_Relationship__c> AccountRelationships;
    
    public ControllerAccountView(ApexPages.StandardController controller){
        Acct = [SELECT Id,
                Owner.Name,
                RecordType.Name,
                RecordTypeId,
                Account_Number__c,
                Customer_PIN__c,
                Salutation,
                Primary_Phone__c,
                FirstName,
                Name,
                Business_Phone__c,
                MiddleName,
                Mobile_Phone__c,
                PersonContact.LastName ,
                Primary_Email__pc,
                Secondary_Approver__c,
                Third_Approver__c ,
                Secondary_Email__pc,
                Account_Status__c,
                CreatedDate,
                Last_Conversation_Date__c,
                Total_Purchases__c,
                Last_Activity_Date__c,
                Account_Agreement_Sent_Date__c,
                Last_Activity_Related__c,
                Account_Agreement_Executed_Date__c,
                Trust_Pilot_Survey_Sent_Date__c,
                Trust_Pilot_Survey_Completed_Date__c,
                Current_Balance__c,
                Storage_Balance__c,
                BillingStreet,
                BillingCity,
                BillingStateCode,
				BillingPostalCode,
				BillingCountryCode,
                Next_Trade_Date__c,
                Next_Trade_Expected_Date__c,
                Next_Trade_Amount__c,
                Trade_Probability__c,
				Gender__c,
                Birthdate__c,
                Marital_Status__c,
                Anniversary__c,
                Spouse_Name__c,
                Is_Loan__c,         
				Last_Lead_Source__c,
                Email_subscription__c,
                IsPersonAccount,
                CRM_Account_GUID__c
                FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        AccountId =ApexPages.currentPage().getParameters().get('id');
         recTypeList = [SELECT Id, Name, IsActive FROM RecordType Where IsActive = true];
    }

    public Account getAcct() {
        return Acct;
    }
    
    public PageReference saveAccount(){
        update Acct;
        return null;
        
    }
    public List<Account_Relationship__c> getAccountRelationships(){        
    	List<Account_Relationship__c> arList = new List<Account_Relationship__c>();            
        arList = [Select Id, Name, From_Account__c, To_Account__c, From_Role__c, To_Role__c From Account_Relationship__c where From_Account__c =: Acct.Id]; 
        return arList;        
    }
    
    public PageReference newAccountRelationship(){
         PageReference page = new  PageReference('/a02/e');
    	 page.setRedirect(true);
    	 return page;
    }
    

    public string GetReportPath(){
      return  GoldlineUtility.GetReportServerLink();
    }
    
    public string setParams(){
        return null;
    }
       
    /* 
     * For use with Accumulation Clients : 012W00000009NALIA2
     * For use with Trust Accounts: 012W000000096KiIAI
     * For use with Estate Accounts: 012W000000096KfIAI
     * For use with Business Accounts: 012W000000096KdIAI
*/
    public string getAccumulationTypeId(){
        for(RecordType rt : recTypeList){
            if(rt.Name == 'Accumulation Client')
                return (string)rt.Id;
        }
        return '';
    }
    public string getTrustTypeId(){
         for(RecordType rt : recTypeList){
            if(rt.Name == 'Trust Account')
                return (string)rt.Id;
        }
        return '';
    }
    public string getEstateTypeId(){
         for(RecordType rt : recTypeList){
            if(rt.Name == 'Estate Account')
                return (string)rt.Id;
        }
        return '';
    }
    public string getBusinessTypeId(){        
         for(RecordType rt : recTypeList){
            if(rt.Name == 'Business Account')
                return (string)rt.Id;
        }
        return '';
    }
}