src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRM_Account_GUID__c</fullName>
        <externalId>true</externalId>
        <label>CRM Account GUID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSynchronizedAX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSynchronizedAX</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>false</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Phone_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Phone Relationships</relationshipLabel>
        <relationshipName>Account_Phone_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phone Number</label>
        <referenceTo>PhoneNumber__c</referenceTo>
        <relationshipLabel>Account Phone Relationships</relationshipLabel>
        <relationshipName>Account_Phone_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Phone Relationship</label>
    <nameField>
        <displayFormat>APRelationship-{YYYY}{00000}</displayFormat>
        <label>Account Phone Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Phone Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PhoneNumber__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PhoneNumberTests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Phone Number</label>
    <nameField>
        <label>Phone Number Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ControllerCreatePersonAccount.cls
public class ControllerCreatePersonAccount {
    //This controller checks duplicate rules on PersonAccount Creation
    //Gives end users to save the duplicate or update current record
    public Account acct {get;set;}
    public Account_Phone_Relationship__c acctRel = new Account_Phone_Relationship__c();
    public PhoneNumber__c phoneNumber = new PhoneNumber__c();
    public ApexPages.StandardController Con {get; set;}
    public String errorDuplicateText{get;set;}
    public List<sObject> duplicateRecords{get;set;}    
    public boolean hasDuplicateResult{get;set;}    
        
    public ControllerCreatePersonAccount(ApexPages.StandardController controller){        
        acct = (Account)controller.getRecord();
        Con = controller;
        hasDuplicateResult = false;
        
    }
        
    public PageReference save() {
        // check for person account record type
        RecordType recType = [select id,name,sobjectType,ispersontype from recordType where ispersontype=true and sobjectType='account' limit 1];
        acct = (Account)Con.getRecord();
        acct.RecordTypeId = recType.id;
        acct.CRM_Account_GUID__c = GuidUtil.NewGUID();
        acct.isSynchronizedAX__C = false;
        Database.SaveResult saveResult = Database.insert(acct, false);
        system.debug('Account>>> '+acct);
        if (!saveResult.isSuccess()) {
            for (Database.Error error : saveResult.getErrors()) {
                // If there are duplicates, an error occurs
                // Process only duplicates and not other errors 
                //   (e.g., validation errors)
                if (error instanceof Database.DuplicateError) {
                    // Handle the duplicate error by first casting it as a 
                    //   DuplicateError class
                    // This lets you use methods of that class 
                    //  (e.g., getDuplicateResult())
                    Database.DuplicateError duplicateError = (Database.DuplicateError)error;
                    Datacloud.DuplicateResult duplicateResult = duplicateError.getDuplicateResult();
                    
                    // Get duplicate records
                    this.duplicateRecords = new List<sObject>();
                    
                    // Return only match results of matching rules that 
                    //  find duplicate records
                    Datacloud.MatchResult[] matchResults = 
                        duplicateResult.getMatchResults();                        
                    // Just grab first match result (which contains the 
                    //   duplicate record found and other match info)
                    Datacloud.MatchResult matchResult = matchResults[0];                        
                    Datacloud.MatchRecord[] matchRecords = matchResult.getMatchRecords();
                    // Add matched record to the duplicate records variable
                    for (Datacloud.MatchRecord matchRecord : matchRecords) {
                        this.duplicateRecords.add(matchRecord.getRecord()); 
                    }
                    // Display duplicate error message as defined in the duplicate rule                    
                    errorDuplicateText = this.duplicateRecords.size() +' Possible Duplicate Records Found.<br/>' + duplicateResult.getErrorMessage();
                    this.hasDuplicateResult = !this.duplicateRecords.isEmpty();                        
                }
            }            
            return null;            
        }         
        try{            
            phoneNumber.Name = acct.Phone; // This will trigger a save into the PhoneNumber__c.Phone_Number__c field
            insert phoneNumber;
            
            acctRel.Account__c = acct.Id;
            acctRel.Phone_Number__c = phoneNumber.Id;
            insert acctRel;
            
            PageReference pageOfNewAccount = New PageReference('/'+acct.id);
            pageOfNewAccount.setRedirect(true);
            return pageOfNewAccount;             
        } catch (Exception e){            
            ApexPages.addMessages(e);
            System.debug('Error in ControllerCreatePersonAccount.save(): ' + e.getMessage());            
        }        
        return null;        
    }
    
    public PageReference saveandignore(){        
        try{            
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true; 
            RecordType recType = [select id,name,sobjectType,ispersontype from recordType where ispersontype=true and sobjectType='account' limit 1];
            acct = (Account)Con.getRecord();
            acct.CRM_Account_GUID__c = GuidUtil.NewGUID();
            acct.isSynchronizedAX__C = false;
            acct.RecordTypeId = recType.id;
            Database.SaveResult saveResult = Database.insert(acct, DML);

            phoneNumber.Name = acct.Phone; // This will trigger a save into the PhoneNumber__c.Phone_Number__c field
            insert phoneNumber;
            
            acctRel.Account__c = acct.Id;
            acctRel.Phone_Number__c = phoneNumber.Id;
            insert acctRel;
            
            PageReference pageOfNewAccount = New PageReference('/'+acct.id);
            pageOfNewAccount.setRedirect(true);
            return pageOfNewAccount;                 
        } catch (Exception e){            
            ApexPages.addMessages(e);
            System.debug('Error in ControllerCreatePersonAccount.saveandignore(): ' + e.getMessage());            
        }        
        return null;        
    }
    
    public PageReference SaveAndNew(){        
        try{            
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true; 
            RecordType recType = [select id,name,sobjectType,ispersontype from recordType where ispersontype=true and sobjectType='account' limit 1];
            acct = (Account)Con.getRecord();
            acct.RecordTypeId = recType.id;
            acct.CRM_Account_GUID__c = GuidUtil.NewGUID();
            acct.isSynchronizedAX__C = false;
            Database.SaveResult saveResult = Database.insert(acct, dml);
            
            //phoneNumber.Name = String.valueOf(acct.Phone).replaceAll('[^0-9]', '');
            insert phoneNumber;
            
            acctRel.Account__c = acct.Id;
            acctRel.Phone_Number__c = phoneNumber.Id;
            insert acctRel;

            phoneNumber.Name = acct.Phone; // This will trigger a save into the PhoneNumber__c.Phone_Number__c field
            insert phoneNumber;
            
            acctRel.Account__c = acct.Id;
            acctRel.Phone_Number__c = phoneNumber.Id;
            insert acctRel;
                                  
            string s ='/apex/CreatePersonAccount';   
            PageReference pg =  new PageReference(s);
            return pg.setRedirect(true) ;
        
        } catch (Exception e){
            
            ApexPages.addMessages(e);
            System.debug('Error in ControllerCreatePersonAccount.SaveAndNew(): ' + e.getMessage());
            
        }
        
        return null;
        
    }

}