src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>false</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (From Account)</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>From_Role__c</fullName>
        <label>From Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Account Holder</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You must select an Individual/Person Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BXm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BPO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (To Account)</relationshipLabel>
        <relationshipName>Account_Relationships_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Role__c</fullName>
        <label>To Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Power of Attorney</fullName>
                </value>
                <value>
                    <fullName>Executor</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referrer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountRelationshipTriggerHandler.cls
public class AccountRelationshipTriggerHandler {
    //this class Handles all trigger events for account relationship
    public static void SwapAccountEntryOnCreate(Account_Relationship__c[]  newAccounts){
        List<Account_Relationship__c> arList = new List<Account_Relationship__c>();
        Account_Relationship__c newAr = new Account_Relationship__c();
        Account_Relationship__c newAr2 = new Account_Relationship__c();
        
        for(Account_Relationship__c ar: newAccounts){
         //   system.debug('>>>>ar.From_Account__c.IsPersonAccount    '+ ar.From_Account__r.IsPersonAccount);
            if(ar.From_Account__c == ar.To_Account__c){
                ar.addError('You cannot create a Relationship from an Account to itself. ');
            }else if(!ar.From_Account__r.IsPersonAccount && !ar.To_Account__r.IsPersonAccount){
            newAr2 = ar;
//            newAr.Name = newAr2.Name;    
            newAr.To_Account__c = newAr2.From_Account__c;
            newAr.From_Account__c = newAr2.To_Account__c;
            newAr.From_Role__c = newAr2.To_Role__c;
            newAr.To_Role__c = newAr2.From_Role__c;
            arList.add(newAr);  
            }
            else{
                ar.addError('You cannot create an Account Relationship between two business-type Accounts');
            }
        }         
        insert arList;
    }
    
}