src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>false</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (From Account)</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>From_Role__c</fullName>
        <label>From Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Account Holder</fullName>
                </value>
                <value>
                    <fullName>Estate</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>You must select an Individual/Person Account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BXm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>0122F0000000BPO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (To Account)</relationshipLabel>
        <relationshipName>Account_Relationships_To</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Role__c</fullName>
        <label>To Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Power of Attorney</fullName>
                </value>
                <value>
                    <fullName>Executor</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Referrer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountRelationshipTriggerHandlerTest.cls
@isTest
private class AccountRelationshipTriggerHandlerTest {
    //Tesst class for AccountRelationship Object Trigger Handler class
    static testMethod void test_SwapAccountEntryOnCreate (){
        Account_Relationship__c ar = new Account_Relationship__c();
        Account acc1 = TestDataFactory.CreateAccountByName('Account 1');
        insert acc1;
        Account acc2 = TestDataFactory.CreateAccountByName('Account 2');
        insert acc2;
       // ar.Name = 'unit test';
        ar.From_Account__c = acc1.Id;
        ar.From_Role__c = 'test from';
        ar.To_Account__c = acc2.Id;
        ar.To_Role__c = 'test to';
        insert ar;
        
        List<Account_Relationship__c> arList = [SELECT Id, From_Account__c, From_Role__c, To_Account__c, To_Role__c 
                                                FROM Account_Relationship__c 
                                                WHERE To_Role__c like '%test%'];
        system.assertEquals(arlist.size() , 2);
        
    }
    static testMethod void test_SwapSameAccountEntryOnCreate (){
        Account_Relationship__c ar = new Account_Relationship__c();
        Account acc1 = TestDataFactory.CreateAccountByName('Account 1');
        insert acc1;
       // ar.Name = 'unit test';
        ar.From_Account__c = acc1.Id;
        ar.From_Role__c = 'test from';
        ar.To_Account__c = acc1.Id;
        ar.To_Role__c = 'test to';
        
        Database.SaveResult saveResult = Database.insert(ar,false);
        if (!saveResult.isSuccess()){
           //for (Database.Error error : saveResult.getErrors()) {                                  
              system.assertEquals(true ,true);
            //}
        }

        
    }
}