src/objects/Metal_Price__c.object
<CustomObject>
    <description>Custom object to hold metal prices</description>
    <fields>
        <fullName>Price_Date__c</fullName>
        <description>Imported price date</description>
        <label>Price Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>The worth of metal</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Metal Price</label>
    <nameField>
        <label>Metal Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metal Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ControllerStockPrice.cls
public class ControllerStockPrice { 
    //this class pulls stock prices from Product table(or AX - based one the system design. TBD)
    public List<Metal_Price__c> ListMP {get;set;}
    
    public ControllerStockPrice(){        
        ListMP = [Select Name, Price__c , Price_Date__c  FROM Metal_Price__c];//add filter for price date, only pull today's numbers
    }
    public List<Metal_Price__c> getMetalPrices(){
        return ListMP;
    }

}